apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: nodejs-pipeline-run
spec:
  pipelineRef:
    name: nodejs-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: git-source
    - name: web-image
      resourceRef:
        name: image-resource