apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: nodejs
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  params:
    - name: gitUrl
      value: https://github.com/SaifRehman/nodejs-tekton-openshift.git
    - name: gitRevision
      value: beta-update
    - name: pathToYamlFile
      value: kubernetes/picalc.yaml
    - name: imageUrl
      value: image-registry.openshift-image-registry.svc.cluster.local:5000/test/nodejs
    - name: imageTag
      value: "1.0"
  serviceAccountName: pipeline
  workspaces:
    - name: git-source
      persistentVolumeClaim:
        claimName: picalc-source-pvc
