apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: url
      value: https://github.com/SaifRehman/nodejs-tekton-openshift.git
    - name: revision
      value: master
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: image-resource
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc.cluster.local:5000/nodejs