apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  params:
    - name: pathToDockerFile
      type: string
      description: The path to the dockerfile to build
      default: $(resources.inputs.docker-source.path)/Dockerfile
    - name: pathToContext
      type: string
      description:
        The build context used by Kaniko
        (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      default: $(resources.inputs.docker-source.path)
  resources:
    inputs:
      - name: docker-source
        type: git
    outputs:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:debug
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
      env:
        - name: "DOCKER_CONFIG"
          value: "/builder/home/.docker"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=image-registry.openshift-image-registry.svc.cluster.local:5000/nodejs/nodejs:latest
        - --context=$(inputs.params.pathToContext)
        - --skip-tls-verify
    - name: run-image
      image: ebits/openshift-client
      command: ["oc"]
      args:
        - apply
        - -f
        - $(inputs.params.pathToContext)/kubernetes/
  volumes:
    - name: docker-config
      configMap: 
        name: docker-config