# apiVersion: tekton.dev/v1alpha1
# kind: Pipeline
# metadata:
#   name: nodejs-build-deploy-pipeline
# spec:
#   resources:
#     - name: git-source
#       type: git
#   tasks:
#     - name: nodejs-build-deploy-pipeline
#       taskRef:
#         name: build-docker-image-from-git-source
#       resources:
#         inputs:
#         - name: git-source
#           resource: git-source
#       params:
#       - name: pathToDockerFile
#         value: Dockerfile
#       - name: pathToContext
#         value: /workspace/nodejs-tekton-openshift-resources


apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodejs-build-deploy-pipeline
spec:
  resources:
    - name: git-source
      type: git
  tasks:
    - name: nodejs-build-deploy-pipeline
      taskRef:
        name: build-docker-image-from-git-source
      params:
        - name: pathToDockerFile
          value: Dockerfile
        - name: pathToContext
          value: /workspace/nodejs-tekton-openshift-resources
      resources:
        inputs:
          - name: git-source
            resource: git-source
    # - name: deploy-web
    #   taskRef:
    #     name: deploy-using-kubectl
    #   resources:
    #     inputs:
    #       - name: git-source
    #         resource: git-source
    #       # - name: image
    #       #   resource: web-image
    #       #   from:
    #       #     - build-skaffold-web
    #   params:
    #   - name: pathToDockerFile
    #     value: Dockerfile
    #   - name: pathToContext
    #     value: /workspace/nodejs-tekton-openshift-resources