apiVersion: v1
kind: DeploymentConfig
metadata:
  name: nodejsdc
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "dev"
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc.cluster.local:5000/test/nodejs:latest
          imagePullPolicy: Always
          name: nodejs
          ports:
            - containerPort: 8080
              protocol: "TCP"