apiVersion: v1
kind: DeploymentConfig
metadata:
  name: nodejsdc
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "dev"
    spec:
      containers:
        - image: __IMAGE__
          imagePullPolicy: Always
          name: nodejs
          ports:
            - containerPort: 8080
              protocol: "TCP"